//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedPermission
    {
        public decimal Permission_ID { get; set; }
        public decimal Page_ID { get; set; }
        public short SystemRole_ID { get; set; }
        public System.DateTimeOffset EnteredOn { get; set; }
        public bool GrantWrite { get; set; }
        public bool GrantDelete { get; set; }
        public decimal EnteredBy_ID { get; set; }
        public Nullable<System.DateTimeOffset> LastModifiedOn { get; set; }
    }
}
