//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public decimal Student_ID { get; set; }
        public string RegNo { get; set; }
        public string Gender { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string MotherTongue { get; set; }
        public string Religion { get; set; }
        public string Caste { get; set; }
        public Nullable<byte> Religion_ID { get; set; }
        public Nullable<int> Language_ID { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<byte> CurrentStd_ID { get; set; }
        public string CurrentDiv { get; set; }
        public string Address { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Mobile3 { get; set; }
        public string HomePh { get; set; }
        public string WorkPh { get; set; }
        public string Email { get; set; }
        public string RFIDTag { get; set; }
        public string AadharNo { get; set; }
        public string PrimaryContact { get; set; }
        public byte[] StudPhoto { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public decimal EnteredBy_ID { get; set; }
        public Nullable<System.DateTimeOffset> EnteredOn { get; set; }
        public decimal LastModifiedBy_ID { get; set; }
        public Nullable<System.DateTimeOffset> LastModifiedOn { get; set; }
    }
}
