//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCredential
    {
        public decimal User_ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public short SystemRole_ID { get; set; }
        public System.DateTimeOffset EnteredOn { get; set; }
        public bool IsActive { get; set; }
        public System.DateTimeOffset LastModifiedOn { get; set; }
    }
}
